<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') { fwrite(STDERR, "migrate_tenants.php must be run from CLI.\n"); exit(1); }
const INCREMENTAL_MIGRATIONS = ['001_schema.sql','005_production_readiness.sql','006_soft_deletes.sql','007_explicit_approvers.sql','008_delegation.sql','009_type_requires_approval.sql','010_contractor_visits.sql','011_visitor_notes.sql','012_gatepass_type_direction.sql','013_phase4_state_machine.sql','014_returnable_item_history.sql','015_phase4_returned_status.sql','016_phase5_gate_operations.sql','017_phase6_notifications.sql'];
$root=dirname(__DIR__);$globalIni=$root.'/config/config.ini';$localIni=$root.'/config/setup.ini';if(!file_exists($globalIni)){fwrite(STDERR,"Missing config/config.ini — copy config/config.ini.example first.\n");exit(1);} $config=parse_ini_file($globalIni,true,INI_SCANNER_TYPED);if(file_exists($localIni)){ $setup=parse_ini_file($localIni,true,INI_SCANNER_TYPED);foreach($setup as $section=>$values){$config[$section]=isset($config[$section])?array_merge($config[$section],$values):$values;}}
$mysqlHost=$config['mysql']['host']??$config['database']['host']??'127.0.0.1';$mysqlPort=(int)($config['mysql']['port']??$config['database']['port']??3306);$mysqlUser=$config['mysql']['username']??$config['database']['username']??'';$mysqlPass=(string)($config['mysql']['password']??$config['database']['password']??'');$masterName=$config['master_db']['name']??'glee_master';if($mysqlUser===''){fwrite(STDERR,"Missing [mysql] username in config.ini — needed to reach every tenant database.\n");exit(1);}
$args=[];foreach($argv as $arg){if(str_starts_with($arg,'--')){if(str_contains($arg,'=')){[$key,$value]=explode('=',substr($arg,2),2);$args[$key]=$value;}else{$args[substr($arg,2)]=true;}}}$dryRun=isset($args['dry-run']);$onlyTenantCode=$args['tenant']??null;$includeInactive=isset($args['include-inactive']);
function db(string $host,int $port,string $user,string $pass,string $dbname):PDO{return new PDO("mysql:host={$host};port={$port};dbname={$dbname};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);}
function runSqlFile(PDO $pdo,string $file):void{$sql=file_get_contents($file);$sql=preg_replace('/--.*(\n|$)/','',$sql);$sql=preg_replace('/\/\*.*?\*\//s','',$sql);$stmts=array_filter(array_map('trim',explode(";\n",$sql)));foreach($stmts as $stmt){if($stmt==='')continue;try{$pdo->exec($stmt);}catch(PDOException $e){$msg=$e->getMessage();if(str_contains($msg,'exists')||str_contains($msg,'Duplicate'))continue;throw $e;}}}
function ensureMigrationsTable(PDO $pdo):void{$pdo->exec("CREATE TABLE IF NOT EXISTS schema_migrations(id bigint unsigned NOT NULL AUTO_INCREMENT,migration varchar(190) NOT NULL,applied_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uk_migration(migration)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
function appliedMigrations(PDO $pdo):array{return $pdo->query('SELECT migration FROM schema_migrations')->fetchAll(PDO::FETCH_COLUMN);}
function tableExists(PDO $pdo,string $table):bool{$stmt=$pdo->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t");$stmt->execute([':t'=>$table]);return(bool)$stmt->fetchColumn();}
function appliedMigrationsSafe(PDO $pdo):array{return tableExists($pdo,'schema_migrations')?appliedMigrations($pdo):[];}
$master=db($mysqlHost,$mysqlPort,$mysqlUser,$mysqlPass,$masterName);$where=$includeInactive?'1=1':'is_active = 1';$bindings=[];if($onlyTenantCode!==null){$where.=' AND code = :code';$bindings[':code']=$onlyTenantCode;}$stmt=$master->prepare("SELECT id, code, name, db_name, is_active FROM tenants WHERE {$where} ORDER BY code");$stmt->execute($bindings);$tenants=$stmt->fetchAll(PDO::FETCH_ASSOC);if(!$tenants){echo $onlyTenantCode!==null?"No tenant found with code \"{$onlyTenantCode}\".\n":"No tenants to process (use --include-inactive to also check disabled tenants).\n";exit(0);}
$migrationsDir=__DIR__;echo "\n== TENANT MIGRATIONS".($dryRun?" (dry run — nothing will be changed)":'')." ==\n";echo count($tenants)." tenant(s) to check: ".implode(', ',array_column($tenants,'code'))."\n";echo "Allowlisted migrations: ".implode(', ',INCREMENTAL_MIGRATIONS)."\n\n";$failures=[];foreach($tenants as $tenant){$label="{$tenant['code']} ({$tenant['db_name']})".($tenant['is_active']?'':' [inactive]');echo "── {$label} ──────────────────────────────\n";try{$tenantDb=db($mysqlHost,$mysqlPort,$mysqlUser,$mysqlPass,$tenant['db_name']);}catch(PDOException $e){echo "  ✗ Could not connect: {$e->getMessage()}\n\n";$failures[]=$tenant['code'].': connection failed';continue;}if(!$dryRun)ensureMigrationsTable($tenantDb);$applied=appliedMigrationsSafe($tenantDb);$ranAny=false;foreach(INCREMENTAL_MIGRATIONS as $migration){if(in_array($migration,$applied,true)){echo "  = {$migration} (already applied)\n";continue;}$file=$migrationsDir.'/'.$migration;if(!file_exists($file)){echo "  ✗ {$migration} — file not found, skipping\n";$failures[]="{$tenant['code']}: missing file {$migration}";continue;}if($dryRun){echo "  → {$migration} (would apply)\n";continue;}try{runSqlFile($tenantDb,$file);$tenantDb->prepare('INSERT INTO schema_migrations (migration) VALUES (:m)')->execute([':m'=>$migration]);echo "  ✓ {$migration} applied\n";$ranAny=true;}catch(Throwable $e){echo "  ✗ {$migration} FAILED: {$e->getMessage()}\n";$failures[]="{$tenant['code']}: {$migration} — {$e->getMessage()}";break;}}if(!$ranAny&&!$dryRun)echo "  (nothing to do)\n";echo "\n";}if($failures){echo "== DONE WITH ERRORS ==\n";foreach($failures as $failure)echo "  - {$failure}\n";echo "\n";exit(1);}echo "== DONE".($dryRun?" (dry run)":'')." — no errors ==\n\n";
