<?php

declare(strict_types=1);

/** Central route-level authorization map. Domain policies remain responsible for record-level checks. */
return [
    'GET' => [
        '#^/dashboard(?:/charts)?$#' => ['dashboard.access'],
        '#^/gatepasses$#' => ['gatepass.view'], '#^/gatepasses/create$#' => ['gatepass.create'], '#^/gatepasses/scan$#' => ['scans.scan'], '#^/gatepasses/scan-history(?:\.json)?$#' => ['scans.view'], '#^/gatepasses/\d+$#' => ['gatepass.view'], '#^/gatepasses/\d+/edit$#' => ['gatepass.update'],
        '#^/visitors$#' => ['visitors.view','gatepass.view_all'], '#^/visitors/create$#' => ['visitors.create','gatepass.create'], '#^/visitors/\d+$#' => ['visitors.view','gatepass.view_all'], '#^/visitors/\d+/edit$#' => ['visitors.update','gatepass.update'],
        '#^/visits$#' => ['visits.view','gatepass.view'], '#^/visits/create$#' => ['visits.create','gatepass.create'], '#^/approvals$#' => ['approval.view'], '#^/approvals/\d+$#' => ['approval.view'], '#^/approvals/\d+/approve$#' => ['approval.approve'], '#^/approvals/\d+/reject$#' => ['approval.reject'],
        '#^/roles$#' => ['roles.view'], '#^/roles/create$#' => ['roles.create'], '#^/roles/\d+/edit$#' => ['roles.update'], '#^/roles/\d+/permissions$#' => ['roles.assign'], '#^/users/\d+/roles$#' => ['roles.assign'],
        '#^/settings$#' => ['settings.view'], '#^/settings/company$#' => ['settings.view'], '#^/settings/theme$#' => ['settings.view'], '#^/settings/gatepass-numbering$#' => ['settings.view'], '#^/settings/badge-numbering$#' => ['settings.view'], '#^/settings/gatepass-types(?:/create|/\d+/edit)?$#' => ['settings.view'], '#^/settings/gatepass-rules$#' => ['settings.view'], '#^/settings/departments$#' => ['settings.view'], '#^/settings/workflows(?:/create|/\d+(?:/edit|/steps(?:/\d+/edit|/\d+/approvers)?)?)$#' => ['settings.view'], '#^/settings/users$#' => ['users.view'], '#^/settings/users/create$#' => ['users.create'], '#^/settings/users/\d+/edit$#' => ['users.update'], '#^/settings/users/profile$#' => ['dashboard.access'], '#^/settings/delegation$#' => ['delegation.view'], '#^/reports$#' => ['reports.view','gatepass.view_all'], '#^/reports/(gatepasses|visitors|visits)$#' => ['reports.view','gatepass.view_all'], '#^/reports/audit-logs$#' => ['audit.view'],
    ],
    'POST' => [
        '#^/gatepasses$#' => ['gatepass.create'], '#^/gatepasses/\d+$#' => ['gatepass.update'], '#^/gatepasses/\d+/delete$#' => ['gatepass.delete'], '#^/gatepasses/\d+/checkin$#' => ['gatepass.checkin'], '#^/gatepasses/\d+/checkout$#' => ['gatepass.checkout'], '#^/gatepasses/\d+/qr/(?:issue|revoke)$#' => ['gatepass.update'], '#^/gatepasses/scan$#' => ['scans.scan'], '#^/gatepasses/previsit/validate$#' => ['scans.scan'], '#^/visits/\d+/previsit-qr/issue$#' => ['visits.previsit_qr_issue'], '#^/visits/\d+/previsit-qr/revoke$#' => ['visits.previsit_qr_revoke'], '#^/visitors$#' => ['visitors.create','gatepass.create'], '#^/visitors/\d+/update$#' => ['visitors.update','gatepass.update'], '#^/visitors/\d+/(?:blacklist|unblacklist)$#' => ['visitors.blacklist','gatepass.update'], '#^/visits$#' => ['visits.create','gatepass.create'], '#^/visits/\d+/checkin$#' => ['visits.checkin','gatepass.checkin'], '#^/visits/\d+/checkout$#' => ['visits.checkout','gatepass.checkout'], '#^/badges/\d+/issue$#' => ['badges.issue','gatepass.checkin'], '#^/badges/\d+/return$#' => ['badges.return','gatepass.checkout'], '#^/approvals/\d+/approve$#' => ['approval.approve'], '#^/approvals/\d+/reject$#' => ['approval.reject'], '#^/roles$#' => ['roles.create'], '#^/roles/\d+$#' => ['roles.update'], '#^/roles/\d+/delete$#' => ['roles.update'], '#^/roles/\d+/permissions$#' => ['roles.assign'], '#^/users/\d+/roles$#' => ['roles.assign'], '#^/settings/company$#' => ['settings.update'], '#^/settings/company/logo$#' => ['settings.update'], '#^/settings/theme(?:/reset)?$#' => ['settings.update'], '#^/settings/gatepass-numbering$#' => ['settings.update'], '#^/settings/badge-numbering$#' => ['settings.update'], '#^/settings/gatepass-types(?:/\d+/update|/store)$#' => ['settings.update'], '#^/settings/gatepass-rules$#' => ['settings.update'], '#^/settings/departments/(?:create|update|toggle|delete)$#' => ['settings.update'], '#^/settings/workflows(?:/\d+(?:/update|/steps(?:/\d+/update|/\d+/approvers)?|/assign)?|)$#' => ['settings.update'], '#^/settings/users$#' => ['users.create'], '#^/settings/users/\d+$#' => ['users.update'], '#^/settings/users/profile$#' => ['dashboard.access'], '#^/settings/delegation$#' => ['delegation.manage'], '#^/settings/delegation/clear$#' => ['delegation.manage'], '#^/reports/(gatepasses|visitors|visits)/export$#' => ['reports.export','gatepass.view_all'], '#^/reports/audit-logs/export$#' => ['audit.export'],
    ],
];
