<?php
namespace App\Modules\Gatepass\Controllers;
use App\Core\Auth;use App\Core\Permission;use App\Core\Request;use App\Core\Response;use App\Core\View;
use App\Modules\Gatepass\Services\GatepassService;use App\Modules\Gatepass\Services\GateSecurityService;use App\Modules\Gatepass\Policies\GatepassPolicy;use App\Modules\Gatepass\Repositories\GatepassTypeRepository;use App\Modules\Gatepass\Repositories\GatepassStatusRepository;use App\Modules\Gatepass\DTOs\GatepassDTO;use App\Modules\Notifications\Services\GatepassNotificationService;
class GatepassController{
 private GatepassService $service;private GatepassPolicy $policy;private GatepassTypeRepository $typeRepo;private GatepassStatusRepository $statusRepo;private GateSecurityService $security;private GatepassNotificationService $notifications;
 public function __construct(){$this->service=new GatepassService();$this->policy=new GatepassPolicy(new Permission(Auth::userId()));$this->typeRepo=new GatepassTypeRepository();$this->statusRepo=new GatepassStatusRepository();$this->security=new GateSecurityService();$this->notifications=new GatepassNotificationService();}
 private function user():array{if(empty($_SESSION['user']))Response::abort(401,'Not authenticated.');return $_SESSION['user'];}
 private function findOrFail(int $id):array{$gatepass=$this->service->find($id);if(!$gatepass)Response::abort(404,'Gatepass not found.');return $gatepass;}
 public function index(Request $request):void{$user=$this->user();$gatepasses=$this->service->list((int)$user['id'],$this->policy->canViewAll());foreach($gatepasses as &$g)$g['actions']=$this->service->getAvailableActions($g);unset($g);View::render('Gatepass::index',['title'=>'Gatepasses','gatepasses'=>$gatepasses,'user'=>$user],'app');}
 public function create(Request $request):void{$user=$this->user();View::render('Gatepass::create',['title'=>'Create Gatepass','types'=>$this->typeRepo->findAll(),'visits'=>$this->service->getVisitsForUser($user['department_id']??null),'user'=>$user,'error'=>$_SESSION['flash']['message']??null],'app');unset($_SESSION['flash']);}
 public function store(Request $request):void{$user=$this->user();try{if(!$this->policy->create())Response::abort(403,"You don't have permission to create gatepasses.");$dto=GatepassDTO::fromRequest($request->all(),(int)$user['id']);$id=$this->service->create($dto);try{$this->security->issueQrCredential($id);}catch(\Throwable $qrError){error_log('Gatepass QR issuance: '.$qrError->getMessage());}try{$created=$this->service->find($id);if($created)$this->notifications->created($id,(string)$created['gatepass_number'],(bool)$created['needs_approval']);}catch(\Throwable $notificationError){error_log('Gatepass creation notification: '.$notificationError->getMessage());}$_SESSION['flash']=['type'=>'success','message'=>'Gatepass created successfully.'];header("Location: /gatepasses/{$id}");exit;}catch(\Throwable $e){$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];header('Location: /gatepasses/create');exit;}}
 public function show(Request $request,int $id):void{$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->view($user,$gatepass))Response::abort(403,"You don't have permission to view this gatepass.");View::render('Gatepass::show',['title'=>'Gatepass '.($gatepass['gatepass_number']??''),'gatepass'=>$gatepass,'items'=>$gatepass['items']??[],'actions'=>$this->service->getAvailableActions($gatepass)],'app');}
 public function issueQr(Request $request,int $id):void{$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->update($user,$gatepass))Response::abort(403,"You don't have permission to manage this gatepass.");try{$this->security->issueQrCredential($id);$_SESSION['flash']=['type'=>'success','message'=>'QR credential regenerated. Any previous QR credential is now invalid.'];}catch(\Throwable $e){$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];}header("Location: /gatepasses/{$id}");exit;}
 public function revokeQr(Request $request,int $id):void{$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->update($user,$gatepass))Response::abort(403,"You don't have permission to manage this gatepass.");try{$revoked=$this->security->revokeQrCredential($id);$_SESSION['flash']=['type'=>$revoked?'success':'warning','message'=>$revoked?'QR credential revoked.':'No active QR credential to revoke.'];}catch(\Throwable $e){$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];}header("Location: /gatepasses/{$id}");exit;}
 public function edit(Request $request,int $id):void{$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->update($user,$gatepass))Response::abort(403,"This gatepass can't be edited.");View::render('Gatepass::edit',['title'=>'Edit Gatepass','gatepass'=>$gatepass,'items'=>$gatepass['items']??[],'types'=>$this->typeRepo->findAll(),'statuses'=>$this->statusRepo->findAll(),'visits'=>$this->service->getVisitsForUser($user['department_id']??null),'error'=>$_SESSION['flash']['message']??null],'app');unset($_SESSION['flash']);}
 public function update(Request $request,int $id):void{$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->update($user,$gatepass))Response::abort(403,"This gatepass can't be edited.");try{$dto=GatepassDTO::fromRequest($request->all(),(int)$user['id']);$this->service->update($id,$dto);$_SESSION['flash']=['type'=>'success','message'=>'Gatepass updated.'];header("Location: /gatepasses/{$id}");exit;}catch(\Throwable $e){$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];header("Location: /gatepasses/{$id}/edit");exit;}}
 public function delete(Request $request,int $id):void{$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->delete($user,$gatepass))Response::abort(403,"This gatepass can't be deleted.");try{$this->service->delete($id);$_SESSION['flash']=['type'=>'success','message'=>'Gatepass deleted.'];}catch(\Throwable $e){$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];}header('Location: /gatepasses');exit;}
 public function checkIn(Request $request,mixed $id):never{$id=(int)$id;$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->checkIn($user,$gatepass)){if($request->wantsJson())Response::json(['success'=>false,'message'=>'Forbidden'],403);Response::abort(403,"You don't have permission to check in this gatepass.");}try{$this->service->checkIn($id,(int)$user['id']);try{$fresh=$this->service->find($id);if($fresh)$this->notifications->checkedIn($id,(string)$fresh['gatepass_number']);}catch(\Throwable $notificationError){error_log('Gatepass check-in notification: '.$notificationError->getMessage());}if($request->wantsJson()){ $gatepass=$this->service->find($id);$actions=$this->service->getAvailableActions($gatepass);Response::json(['success'=>true,'message'=>'Checked in successfully.','status_name'=>$gatepass['status_name']??null,'status_code'=>strtolower($gatepass['status_code']??''),'can_checkin'=>(bool)($actions['can_checkin']??false),'can_checkout'=>(bool)($actions['can_checkout']??false)]);}$_SESSION['flash']=['type'=>'success','message'=>'Checked in successfully.'];}catch(\Throwable $e){if($request->wantsJson())Response::json(['success'=>false,'message'=>$e->getMessage()],400);$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];}header("Location: /gatepasses/{$id}");exit;}
 public function checkOut(Request $request,mixed $id):never{$id=(int)$id;$user=$this->user();$gatepass=$this->findOrFail($id);if(!$this->policy->checkOut($user,$gatepass)){if($request->wantsJson())Response::json(['success'=>false,'message'=>'Forbidden'],403);Response::abort(403,"You don't have permission to check out this gatepass.");}try{$this->service->checkOut($id,(int)$user['id']);try{$fresh=$this->service->find($id);if($fresh)$this->notifications->checkedOut($id,(string)$fresh['gatepass_number']);}catch(\Throwable $notificationError){error_log('Gatepass check-out notification: '.$notificationError->getMessage());}if($request->wantsJson()){ $gatepass=$this->service->find($id);$actions=$this->service->getAvailableActions($gatepass);Response::json(['success'=>true,'message'=>'Checked out successfully.','status_name'=>$gatepass['status_name']??null,'status_code'=>strtolower($gatepass['status_code']??''),'can_checkin'=>(bool)($actions['can_checkin']??false),'can_checkout'=>(bool)($actions['can_checkout']??false)]);}$_SESSION['flash']=['type'=>'success','message'=>'Checked out successfully.'];}catch(\Throwable $e){if($request->wantsJson())Response::json(['success'=>false,'message'=>$e->getMessage()],400);$_SESSION['flash']=['type'=>'danger','message'=>$e->getMessage()];}header("Location: /gatepasses/{$id}");exit;}
}